### ISSUE TITLE
Add rowClick or rowDblClick event

### ISSUE THREAD

**Issue by lairdresearch** [gzimbron/svelte-datagrid#36]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Similar to the tabulator-tables library, adding these events so that when a row is clicked, it triggers an event with the selected row's data added.

### What type of pull request would this be?

Enhancement

**Comment by gzimbron** [comment]
Thanks for the suggestion, I added these events to rows on v0.4.0! 🚀
