### ISSUE TITLE
Column widths as a % of the table using css scaling, not just pixels.

### ISSUE THREAD

**Issue by lairdresearch** [gzimbron/svelte-datagrid#37]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Rather than pixels, be able to specify something like "make this column use up any remaining space"

### What type of pull request would this be?

Enhancement

**Comment by gzimbron** [comment]
Percentage widths cannot be used at the moment, because the grid is a "virtual" table whose position is calculated based on the width and height of each cell.
